### ISSUE TITLE
What is hg19-blacklist.v2.bed.gz

### ISSUE THREAD

**Issue by Rohit-Satyam** [Boyle-Lab/Blacklist#11]
Hi!

I am a bit confused about the file named  hg19-blacklist.v2.bed.gz. It contains 834 Blacklisted regions while the google sheet Merged lists contain merely 412 regions. Which blacklist must be ultimately used. How do they differ? I couldn't find an answer to this in your paper as well.

**Comment by aboyle** [comment]
We don't maintain a google sheet for the automated blacklist. I am not sure what you are referring to.

**Comment by Rohit-Satyam** [comment]
This one was given in the README pdf: https://docs.google.com/spreadsheets/d/1s_LNh4uAD3aIrr4TbOji7ehDMiFs0av0OD7prOk0jkA/edit?hl=en&hl=en#gid=5

**Comment by aboyle** [comment]
I believe this was the DAC blacklist from ENCODE. The list provided here is the fully automated without manual curation.
