### ISSUE TITLE
hg38 blacklist confusion

### ISSUE THREAD

**Issue by rauldiul** [Boyle-Lab/Blacklist#18]
Hi!

thanks for your resource.

I have a comment regarding the blacklists for hg38 which you describe at the end of the `README.md` file. I understand these are the "older" DAC blacklists (not the newer ones which you describe in the 2019 paper 10.1038/s41598-019-45839-z)

I have noticed that the hg38 blacklist which you link to in the `README.md` is not the same between the two links: the file in the first link is much shorter than the one in the ENCODE website.

- HUMAN (hg19/GRCh38): http://mitra.stanford.edu/kundaje/akundaje/release/blacklists/hg38-human/hg38.blacklist.bed.gz ENCODE portal link: https://www.encodeproject.org/annotations/ENCSR636HFF/ (Select GRCh38)

I checked the mouse files, for example, and they do point to the same files. So I don't know if for hg38 the two links are supposed to also have the same file.

- MOUSE (mm10): http://mitra.stanford.edu/kundaje/akundaje/release/blacklists/mm10-mouse/mm10.blacklist.bed.gz ENCODE portal link: https://www.encodeproject.org/annotations/ENCSR636HFF/ (Select mm10) 

Finally, just to be safe that I'm not confused, if I want to use the **newer** (improved) blacklists, derived from your 2019 paper, these are the ones in the `/lists` folder containing the "v2" string in their names, right?

thanks for your help!

**Comment by aboyle** [comment]
Thank you for pointing this out. There were multiple iterations of the ENCODE GRCh38 blacklist over time. The most current is the v2 blacklist in this repository.
