### ISSUE TITLE
Did not manage to build Blacklist.

### ISSUE THREAD

**Issue by SimonBourdareau** [Boyle-Lab/Blacklist#2]
Dear Alan,

Thanks for the official release of Blacklist, I hope it will be useful for every genomic lab even those working on non-model organisms. 

I try since several days to build Blacklist and the file that I get from the compiler is wrong. It seems something is broken inside the code of blacklist.cpp or in the Makefile. Or maybe I didn't use the proper version of g++?

Currently I try to build it on a ubuntu 18.04 LTS machine with the g++ version 7.4.0

Best,
Simon

**Comment by aboyle** [comment]
Please provide a little more information such as the errors that you are encountering.

**Comment by SimonBourdareau** [comment]
I followed the instructions provided in the Readme file.

and after I had compiled Blacklist, if I try : 
./Blacklist

I get this error:
./Blacklist: symbol lookup error: ./Blacklist: undefined symbol: _ZNK8BamTools9BamReader14GetReferenceIDERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

Simon

**Comment by aboyle** [comment]
I am unable to reproduce this error on Unbuntu 18.04 using gcc 7.4.0. Symbol lookup error is a problem with linking so it sounds like you might have a problem in the bamtools compilation step.
