### ISSUE TITLE
Ubuntu issue

### ISSUE THREAD

**Issue by bolton-lab** [Boyle-Lab/Blacklist#21]
I have now compiled on Ubuntu and getting error:

`./Blacklist: error while loading shared libraries: libbamtools.so.2.4.1: cannot open shared object file: No such file or directory`

**Comment by aboyle** [comment]
This error says that bamtools is not available for linking. Please make sure that you are compiling bamtools correctly in the installation of the program.

**Comment by bolton-lab** [comment]
Thanks @aboyle but I compiled exactly as indicated in the Markdown.  Is there a different way?

**Comment by aboyle** [comment]
No. Presumably you are getting an error when installing bamtools. The blacklist program requires bamtools to be installed to properly compile.

**Comment by ghost** [comment]
This docker builds and compiles bamtools correct but still get error:

```
FROM ubuntu:18.04
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y less samtools git wget nano vim
RUN apt-get update && apt-get install -y unzip make gcc g++ cmake
RUN apt-get update && apt-get install -y zlib1g-dev

RUN cd /opt && git clone --recurse-submodules https://github.com/Boyle-Lab/Blacklist.git && \
	cd Blacklist/bamtools/ && \
    mkdir build && \
    cd build && \
    cmake -DCMAKE_INSTALL_PREFIX:PATH=$(cd ..; pwd)/install .. && \
    make && \
    make install && \
    cd ../..
```

I run from the `/opt/Blacklist/demo` folder and the shared library is in `/opt/Blacklist/bamtools/lib/libbamtools.so.2.4.1`.  Maybe the bamtools libraries need to be installed in `/usr/local/lib` and not in `Blacklist/bamtools/lib`

**Comment by ghost** [comment]
OMG you need to copy the compiled Blacklist in the folder Blacklist to demo folder.  The one in there is just from the repo.  That makes sense.  Now I get it to run on the demo but it indicates `Unable to read mappability files!`

I am using these `*.Unique.Mappability.bb` files here http://hgdownload.soe.ucsc.edu/gbdb/hg38/hoffmanMappability/?C=M;O=D
