### ISSUE TITLE
Question for WES

### ISSUE THREAD

**Issue by ghost** [Boyle-Lab/Blacklist#23]
I have a question.  I have a Whole Exome sequencing experiment with 161 bam files.  I ran Blacklist and for some chromosomes there are many regions but for chr3, chr4, chr5, and chr6 the entire chromosomes are High Signal Region.  What does this mean?

```
chr3    0       198295500       High Signal Region
chr4    0       190214500       High Signal Region
chr5    0       181538200       High Signal Region
chr6    0       170805900       High Signal Region
```

**Comment by aboyle** [comment]
I am not sure why this would be without seeing the data. The application is not written to take exome sequencing as input so there might be some unexpected results due to that. You should be able to just use the existing blacklist for this situation.

**Comment by aboyle** [comment]
Following up on this, I am certain that trying to call abnormal signal regions using WES is going to essentially mask all of the genes. You should use a blacklist derived from input sequence (or use an existing blacklist). WES data will appear to be aberrant signal when compared to the genome wide lack of signal.

**Comment by ghost** [comment]
Thanks, I forget what the results where before but with using this file https://www.encodeproject.org/files/ENCFF356LFX/, there were only 15 variants from over few hundred-thousand that were in these regions.
