### ISSUE TITLE
A little confused about the input files.

### ISSUE THREAD

**Issue by Reemann** [Boyle-Lab/Blacklist#26]
I'm a little confused about the `input/` and `mappability/` directory. Is it possible to generate the `.sam` files if I only have a `.fa` file of a species like zebrafish? Or is there somewhere to download these files?

**Comment by aboyle** [comment]
Sam files are generated from aligning your input data to the reference. You can not currently generate a blacklist using only a reference.

**Comment by Reemann** [comment]
> Sam files are generated from aligning your input data to the reference. You can not currently generate a blacklist using only a reference.

I was too young to understand the blacklist a year ago, but I understand it now. Thanks a lot to your reply!
