### ISSUE TITLE
discrepancy between hg38-blacklist.v2.bed and hg38 blacklist on ENCODE

### ISSUE THREAD

**Issue by naumanjaved** [Boyle-Lab/Blacklist#28]
Hello,

Thanks for this resource. There seems to be a large discrepancy between the v2 blacklist for hg38 listed here and the ENCODE hg38 blacklist(https://www.encodeproject.org/annotations/ENCSR636HFF/). I was wondering why there is such a discrepancy and which version I should be using. Example:

![image](https://user-images.githubusercontent.com/14824947/139465933-f18808d3-562e-4195-b97a-3bca8062dbe8.png)

In general it looks like the regions in the github version(top) are longer and overlap less with the ENCODE version in centromeric regions

**Comment by aboyle** [comment]
Please see the [README.txt](https://github.com/Boyle-Lab/Blacklist/files/7444631/README.txt) for the ENCODE track which represents a combination of multiple lists.
