### ISSUE TITLE
The whole chromosome is output instead of blacklist

### ISSUE THREAD

**Issue by KRhoDomb** [Boyle-Lab/Blacklist#29]
Hi,

I need help with building blacklist for my small plant genome (Marchantia polymorpha, ~280 Mbp total, 9 chromosoms between 30 and 7.5 Mbp).
I tried Blacklist on demo data and it runs ok. When I run it on any of my chromosomes, using its respective input bam file and umap mappability file, it outputs the whole chromosome (e.g.  chr1  0  30584100 High Signal Region).
I know there are a few regions with excessive coverage in the genome, because I see them in genome browser in every CHIP-seq input file. 
Do you have any idea? I'll be really grateful for any help!

Best,
Rotem

**Comment by aboyle** [comment]
The software relies on identification of outliers in a large set of input data. A single input file is not going to give any reasonable output. We would recommend many more input files. We used 1256, 287, 443, and 490 for human, mouse, fly, and worm.
