### ISSUE TITLE
Building custom blacklist

### ISSUE THREAD

**Issue by adrdufour** [Boyle-Lab/Blacklist#31]
Hi,

I'm investigating the building of a blacklist for pigs, and I wonder how many chip-seq tracks I need and which type of data (input or controls ?).

I'm also seeking the code necessary to map the fastq and split them by chromosomes.

Thanks for your helps,
Adrien Dufour.

**Comment by aboyle** [comment]
In generation of the blacklist we used the input control from ChIP-seq experiments (wither just fragmented genomic DNA or igg pulldown). I think you probably need more than 100 input tracks for a quality blacklist. We used 1256, 287, 443, and 490 for human, mouse, fly, and worm.
