### ISSUE TITLE
Poorly formatted BED record error

### ISSUE THREAD

**Issue by bennywithaG** [Boyle-Lab/Blacklist#35]
Hello, 

I downloaded the mm10-blacklist.v2.bed.gz file and tried to use that in an argument for the Genrich peak caller (-E mm10-blacklist.v2.bed.gz). However I my script failed with the following message. "Error: Poorly Formatted BED record". 

I do not get the error message if I remove the -E mm10-blacklist.v2.bed.gz argument.  

Do I need to sort the blacklist BED file before using it?

Thanks.

**Comment by aboyle** [comment]
The file with a `gz` extension is a compressed file (think zip). Your software probably requires an uncompressed file so you need to use `gunzip mm10-blacklist.v2.bed.gz` or any other available software to unzip the file.
