### ISSUE TITLE
g++: error: unrecognized command line option ‘-std=c++14’

### ISSUE THREAD

**Issue by qiaowei-vvjoe** [Boyle-Lab/Blacklist#4]
Hi dear Boyle
Thank you so much for developing this Blacklist.
Now I would like to use hg38-blacklist.v2.bed.gz to filter ATACseq data using -e , --blacklist <BED> in HMMRATAC,but there are some warnings and 1 error when I install in **CentOS Linux 7 (Core)**.
`[qiaowei@clust1 build]$ make
Scanning dependencies of target SharedHeaders
[  1%] Exporting SharedHeaders
[  1%] Built target SharedHeaders
Scanning dependencies of target APIHeaders
[  2%] Exporting APIHeaders
[  2%] Built target APIHeaders
Scanning dependencies of target AlgorithmsHeaders
[  3%] Exporting AlgorithmsHeaders
[  3%] Built target AlgorithmsHeaders
Scanning dependencies of target BamTools
[  4%] Building CXX object src/api/CMakeFiles/BamTools.dir/BamAlignment.cpp.o
[  5%] Building CXX object src/api/CMakeFiles/BamTools.dir/BamMultiReader.cpp.o
[  6%] Building CXX object src/api/CMakeFiles/BamTools.dir/BamReader.cpp.o
[  7%] Building CXX object src/api/CMakeFiles/BamTools.dir/BamWriter.cpp.o
[  8%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamHeader.cpp.o
[  9%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamProgram.cpp.o
[ 10%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamProgramChain.cpp.o
[ 11%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamReadGroup.cpp.o
[ 12%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamReadGroupDictionary.cpp.o
[ 13%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamSequence.cpp.o
[ 14%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamSequenceDictionary.cpp.o
[ 15%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/bam/BamHeader_p.cpp.o
[ 16%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/bam/BamMultiReader_p.cpp.o
[ 17%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/bam/BamRandomAccessController_p.cpp.o
[ 18%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/bam/BamReader_p.cpp.o
[ 19%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/bam/BamWriter_p.cpp.o
[ 20%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/index/BamIndexFactory_p.cpp.o
[ 21%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/index/BamStandardIndex_p.cpp.o
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/api/internal/index/BamStandardIndex_p.cpp: In member function ‘void BamTools::Internal::BamStandardIndex::WriteLinearOffsets(const int&, BamTools::Internal::BaiLinearOffsetVector&)’:
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/api/internal/index/BamStandardIndex_p.cpp:958:89: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if ( numBytesWritten != (sizeof(offsetCount) + linearOffsets.size()*sizeof(uint64_t)) )
                                                                                         ^
[ 22%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/index/BamToolsIndex_p.cpp.o
[ 23%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/BamDeviceFactory_p.cpp.o
[ 24%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/BamFile_p.cpp.o
[ 25%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/BamFtp_p.cpp.o
[ 26%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/BamHttp_p.cpp.o
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/api/internal/io/BamHttp_p.cpp: In member function ‘bool BamTools::Internal::BamHttp::SendGetRequest(size_t)’:
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/api/internal/io/BamHttp_p.cpp:409:62: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if ( WriteToSocket(requestHeader.c_str(), headerSize) != headerSize ) {
                                                              ^
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/api/internal/io/BamHttp_p.cpp: In member function ‘bool BamTools::Internal::BamHttp::SendHeadRequest()’:
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/api/internal/io/BamHttp_p.cpp:501:62: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if ( WriteToSocket(requestHeader.c_str(), headerSize) != headerSize ) {
                                                              ^
[ 27%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/BamPipe_p.cpp.o
[ 28%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/BgzfStream_p.cpp.o
[ 29%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/ByteArray_p.cpp.o
[ 30%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/HostAddress_p.cpp.o
[ 31%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/HostInfo_p.cpp.o
[ 32%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/HttpHeader_p.cpp.o
[ 33%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/ILocalIODevice_p.cpp.o
[ 34%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/RollingBuffer_p.cpp.o
[ 35%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/TcpSocket_p.cpp.o
[ 36%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/TcpSocketEngine_p.cpp.o
[ 37%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/TcpSocketEngine_unix_p.cpp.o
[ 38%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/sam/SamFormatParser_p.cpp.o
[ 39%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/sam/SamFormatPrinter_p.cpp.o
[ 40%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/sam/SamHeaderValidator_p.cpp.o
[ 41%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/utils/BamException_p.cpp.o
Linking CXX shared library ../../../lib/libbamtools.so
[ 41%] Built target BamTools
Scanning dependencies of target BamTools-static
[ 42%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/BamAlignment.cpp.o
[ 43%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/BamMultiReader.cpp.o
[ 44%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/BamReader.cpp.o
[ 45%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/BamWriter.cpp.o
[ 46%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/SamHeader.cpp.o
[ 47%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/SamProgram.cpp.o
[ 48%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/SamProgramChain.cpp.o
[ 49%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/SamReadGroup.cpp.o
[ 50%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/SamReadGroupDictionary.cpp.o
[ 51%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/SamSequence.cpp.o
[ 52%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/SamSequenceDictionary.cpp.o
[ 53%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/bam/BamHeader_p.cpp.o
[ 54%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/bam/BamMultiReader_p.cpp.o
[ 55%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/bam/BamRandomAccessController_p.cpp.o
[ 56%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/bam/BamReader_p.cpp.o
[ 57%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/bam/BamWriter_p.cpp.o
[ 58%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/index/BamIndexFactory_p.cpp.o
[ 59%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/index/BamStandardIndex_p.cpp.o
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/api/internal/index/BamStandardIndex_p.cpp: In member function ‘void BamTools::Internal::BamStandardIndex::WriteLinearOffsets(const int&, BamTools::Internal::BaiLinearOffsetVector&)’:
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/api/internal/index/BamStandardIndex_p.cpp:958:89: **warning: comparison between signed and unsigned integer expressions [-Wsign-compare]**
     if ( numBytesWritten != (sizeof(offsetCount) + linearOffsets.size()*sizeof(uint64_t)) )
                                                                                         ^
[ 60%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/index/BamToolsIndex_p.cpp.o
[ 61%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/io/BamDeviceFactory_p.cpp.o
[ 62%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/io/BamFile_p.cpp.o
[ 63%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/io/BamFtp_p.cpp.o
[ 64%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/io/BamHttp_p.cpp.o
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/api/internal/io/BamHttp_p.cpp: In member function ‘bool BamTools::Internal::BamHttp::SendGetRequest(size_t)’:
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/api/internal/io/BamHttp_p.cpp:409:62: **warning: comparison between signed and unsigned integer expressions [-Wsign-compare]**
     if ( WriteToSocket(requestHeader.c_str(), headerSize) != headerSize ) {
                                                              ^
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/api/internal/io/BamHttp_p.cpp: In member function ‘bool BamTools::Internal::BamHttp::SendHeadRequest()’:
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/api/internal/io/BamHttp_p.cpp:501:62: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if ( WriteToSocket(requestHeader.c_str(), headerSize) != headerSize ) {
                                                              ^
[ 65%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/io/BamPipe_p.cpp.o
[ 66%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/io/BgzfStream_p.cpp.o
[ 67%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/io/ByteArray_p.cpp.o
[ 68%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/io/HostAddress_p.cpp.o
[ 69%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/io/HostInfo_p.cpp.o
[ 70%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/io/HttpHeader_p.cpp.o
[ 71%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/io/ILocalIODevice_p.cpp.o
[ 72%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/io/RollingBuffer_p.cpp.o
[ 73%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/io/TcpSocket_p.cpp.o
[ 74%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/io/TcpSocketEngine_p.cpp.o
[ 75%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/io/TcpSocketEngine_unix_p.cpp.o
[ 76%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/sam/SamFormatParser_p.cpp.o
[ 77%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/sam/SamFormatPrinter_p.cpp.o
[ 78%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/sam/SamHeaderValidator_p.cpp.o
[ 79%] Building CXX object src/api/CMakeFiles/BamTools-static.dir/internal/utils/BamException_p.cpp.o
Linking CXX static library ../../../lib/libbamtools.a
[ 79%] Built target BamTools-static
Scanning dependencies of target jsoncpp
[ 80%] Building CXX object src/third_party/jsoncpp/CMakeFiles/jsoncpp.dir/json_reader.cpp.o
[ 81%] Building CXX object src/third_party/jsoncpp/CMakeFiles/jsoncpp.dir/json_value.cpp.o
[ 82%] Building CXX object src/third_party/jsoncpp/CMakeFiles/jsoncpp.dir/json_writer.cpp.o
Linking CXX static library ../../../../lib/libjsoncpp.a
[ 82%] Built target jsoncpp
Scanning dependencies of target BamTools-utils
[ 83%] Building CXX object src/utils/CMakeFiles/BamTools-utils.dir/bamtools_fasta.cpp.o
[ 84%] Building CXX object src/utils/CMakeFiles/BamTools-utils.dir/bamtools_options.cpp.o
[ 85%] Building CXX object src/utils/CMakeFiles/BamTools-utils.dir/bamtools_pileup_engine.cpp.o
[ 86%] Building CXX object src/utils/CMakeFiles/BamTools-utils.dir/bamtools_utilities.cpp.o
Linking CXX static library ../../../lib/libbamtools-utils.a
[ 86%] Built target BamTools-utils
Scanning dependencies of target bamtools_cmd
[ 87%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_convert.cpp.o
[ 88%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_count.cpp.o
[ 89%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_coverage.cpp.o
[ 90%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_filter.cpp.o
[ 91%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_header.cpp.o
[ 92%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_index.cpp.o
[ 93%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_merge.cpp.o
[ 94%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_random.cpp.o
[ 95%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_resolve.cpp.o
[ 96%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_revert.cpp.o
[ 97%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_sort.cpp.o
[ 98%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_split.cpp.o
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/toolkit/bamtools_split.cpp: In member function ‘bool BamTools::SplitTool::SplitToolPrivate::SplitListTagImpl(BamTools::BamAlignment&)’:
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/toolkit/bamtools_split.cpp:474:23: warning: typedef ‘TagElementType’ locally defined but not used [-Wunused-local-typedefs]
     typedef T         TagElementType;
                       ^
In file included from /mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/api/BamReader.h:14:0,
                 from /mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/toolkit/bamtools_split.cpp:14:
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/api/BamAlignment.h: In instantiation of ‘bool BamTools::BamAlignment::GetTag(const string&, std::vector<T>&) const [with T = signed char; std::string = std::basic_string<char>]’:
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/toolkit/bamtools_split.cpp:499:13:   required from ‘bool BamTools::SplitTool::SplitToolPrivate::SplitListTagImpl(BamTools::BamAlignment&) [with T = signed char]’
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/toolkit/bamtools_split.cpp:415:95:   required from here
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/api/BamAlignment.h:581:9: warning: variable ‘elementLength’ set but not used [-Wunused-but-set-variable]
     int elementLength = 0;
         ^
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/api/BamAlignment.h: In instantiation of ‘bool BamTools::BamAlignment::GetTag(const string&, std::vector<T>&) const [with T = short int; std::string = std::basic_string<char>]’:
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/toolkit/bamtools_split.cpp:499:13:   required from ‘bool BamTools::SplitTool::SplitToolPrivate::SplitListTagImpl(BamTools::BamAlignment&) [with T = short int]’
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/toolkit/bamtools_split.cpp:416:96:   required from here
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/api/BamAlignment.h:581:9: **warning: variable ‘elementLength’ set but not used [-Wunused-but-set-variable]**
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/api/BamAlignment.h: In instantiation of ‘bool BamTools::BamAlignment::GetTag(const string&, std::vector<T>&) const [with T = int; std::string = std::basic_string<char>]’:
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/toolkit/bamtools_split.cpp:499:13:   required from ‘bool BamTools::SplitTool::SplitToolPrivate::SplitListTagImpl(BamTools::BamAlignment&) [with T = int]’
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/toolkit/bamtools_split.cpp:417:96:   required from here
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/api/BamAlignment.h:581:9: **warning: variable ‘elementLength’ set but not used [-Wunused-but-set-variable]**
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/api/BamAlignment.h: In instantiation of ‘bool BamTools::BamAlignment::GetTag(const string&, std::vector<T>&) const [with T = unsigned char; std::string = std::basic_string<char>]’:
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/toolkit/bamtools_split.cpp:499:13:   required from ‘bool BamTools::SplitTool::SplitToolPrivate::SplitListTagImpl(BamTools::BamAlignment&) [with T = unsigned char]’
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/toolkit/bamtools_split.cpp:418:96:   required from here
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/api/BamAlignment.h:581:9: **warning: variable ‘elementLength’ set but not used [-Wunused-but-set-variable]**
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/api/BamAlignment.h: In instantiation of ‘bool BamTools::BamAlignment::GetTag(const string&, std::vector<T>&) const [with T = short unsigned int; std::string = std::basic_string<char>]’:
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/toolkit/bamtools_split.cpp:499:13:   required from ‘bool BamTools::SplitTool::SplitToolPrivate::SplitListTagImpl(BamTools::BamAlignment&) [with T = short unsigned int]’
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/toolkit/bamtools_split.cpp:419:97:   required from here
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/api/BamAlignment.h:581:9: **warning: variable ‘elementLength’ set but not used [-Wunused-but-set-variable]**
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/api/BamAlignment.h: In instantiation of ‘bool BamTools::BamAlignment::GetTag(const string&, std::vector<T>&) const [with T = unsigned int; std::string = std::basic_string<char>]’:
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/toolkit/bamtools_split.cpp:499:13:   required from ‘bool BamTools::SplitTool::SplitToolPrivate::SplitListTagImpl(BamTools::BamAlignment&) [with T = unsigned int]’
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/toolkit/bamtools_split.cpp:420:97:   required from here
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/api/BamAlignment.h:581:9: **warning: variable ‘elementLength’ set but not used [-Wunused-but-set-variable]**
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/api/BamAlignment.h: In instantiation of ‘bool BamTools::BamAlignment::GetTag(const string&, std::vector<T>&) const [with T = float; std::string = std::basic_string<char>]’:
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/toolkit/bamtools_split.cpp:499:13:   required from ‘bool BamTools::SplitTool::SplitToolPrivate::SplitListTagImpl(BamTools::BamAlignment&) [with T = float]’
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/toolkit/bamtools_split.cpp:421:94:   required from here
/mnt/disk1/qiaowei/reference/Blacklist/bamtools/src/api/BamAlignment.h:581:9: **warning: variable ‘elementLength’ set but not used [-Wunused-but-set-variable]**
[ 99%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_stats.cpp.o
[100%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools.cpp.o
Linking CXX executable ../../../bin/bamtools
[100%] Built target bamtools_cmd
[qiaowei@clust1 build]$ l
total 40K
drwxrwxr-x. 4 qiaowei qiaowei 4.0K Oct  5 22:48 CMakeFiles
drwxrwxr-x. 7 qiaowei qiaowei 4.0K Oct  5 22:45 src
-rw-rw-r--. 1 qiaowei qiaowei 1.9K Oct  5 22:45 cmake_install.cmake
-rw-rw-r--. 1 qiaowei qiaowei 9.0K Oct  5 22:45 Makefile
-rw-rw-r--. 1 qiaowei qiaowei  13K Oct  5 22:45 CMakeCache.txt
[qiaowei@clust1 build]$ make install
[  1%] Exporting SharedHeaders
[  1%] Built target SharedHeaders
[  2%] Exporting APIHeaders
[  2%] Built target APIHeaders
[  3%] Exporting AlgorithmsHeaders
[  1%] Exporting SharedHeaders
[  1%] Built target SharedHeaders
[  2%] Exporting APIHeaders
[  2%] Built target APIHeaders
[  3%] Exporting AlgorithmsHeaders
[  3%] Built target AlgorithmsHeaders
[ 41%] Built target BamTools
[ 79%] Built target BamTools-static
[ 82%] Built target jsoncpp
[ 86%] Built target BamTools-utils
[100%] Built target bamtools_cmd
Install the project...
-- Install configuration: "Release"
-- Installing: /mnt/disk1/qiaowei/reference/Blacklist/bamtools/install/include/bamtools/shared/bamtools_global.h
-- Installing: /mnt/disk1/qiaowei/reference/Blacklist/bamtools/install/lib/bamtools/libbamtools.so.2.4.1
-- Installing: /mnt/disk1/qiaowei/reference/Blacklist/bamtools/install/lib/bamtools/libbamtools.so
-- Installing: /mnt/disk1/qiaowei/reference/Blacklist/bamtools/install/lib/bamtools/libbamtools.a
-- Installing: /mnt/disk1/qiaowei/reference/Blacklist/bamtools/install/include/bamtools/api/api_global.h
-- Installing: /mnt/disk1/qiaowei/reference/Blacklist/bamtools/install/include/bamtools/api/BamAlgorithms.h
-- Installing: /mnt/disk1/qiaowei/reference/Blacklist/bamtools/install/include/bamtools/api/BamAlignment.h
-- Installing: /mnt/disk1/qiaowei/reference/Blacklist/bamtools/install/include/bamtools/api/BamAux.h
-- Installing: /mnt/disk1/qiaowei/reference/Blacklist/bamtools/install/include/bamtools/api/BamConstants.h
-- Installing: /mnt/disk1/qiaowei/reference/Blacklist/bamtools/install/include/bamtools/api/BamIndex.h
-- Installing: /mnt/disk1/qiaowei/reference/Blacklist/bamtools/install/include/bamtools/api/BamMultiReader.h
-- Installing: /mnt/disk1/qiaowei/reference/Blacklist/bamtools/install/include/bamtools/api/BamReader.h
-- Installing: /mnt/disk1/qiaowei/reference/Blacklist/bamtools/install/include/bamtools/api/BamWriter.h
-- Installing: /mnt/disk1/qiaowei/reference/Blacklist/bamtools/install/include/bamtools/api/IBamIODevice.h
-- Installing: /mnt/disk1/qiaowei/reference/Blacklist/bamtools/install/include/bamtools/api/SamConstants.h
-- Installing: /mnt/disk1/qiaowei/reference/Blacklist/bamtools/install/include/bamtools/api/SamHeader.h
-- Installing: /mnt/disk1/qiaowei/reference/Blacklist/bamtools/install/include/bamtools/api/SamProgram.h
-- Installing: /mnt/disk1/qiaowei/reference/Blacklist/bamtools/install/include/bamtools/api/SamProgramChain.h
-- Installing: /mnt/disk1/qiaowei/reference/Blacklist/bamtools/install/include/bamtools/api/SamReadGroup.h
-- Installing: /mnt/disk1/qiaowei/reference/Blacklist/bamtools/install/include/bamtools/api/SamReadGroupDictionary.h
-- Installing: /mnt/disk1/qiaowei/reference/Blacklist/bamtools/install/include/bamtools/api/SamSequence.h
-- Installing: /mnt/disk1/qiaowei/reference/Blacklist/bamtools/install/include/bamtools/api/SamSequenceDictionary.h
-- Installing: /mnt/disk1/qiaowei/reference/Blacklist/bamtools/install/include/bamtools/api/algorithms/Sort.h
-- Installing: /mnt/disk1/qiaowei/reference/Blacklist/bamtools/install/bin/bamtools-2.4.1
-- Installing: /mnt/disk1/qiaowei/reference/Blacklist/bamtools/install/bin/bamtools
-- Removed runtime path from "/mnt/disk1/qiaowei/reference/Blacklist/bamtools/install/bin/bamtools-2.4.1"
[qiaowei@clust1 build]$ l
total 44K
-rw-rw-r--. 1 qiaowei qiaowei 2.2K Oct  5 22:51 install_manifest.txt
drwxrwxr-x. 4 qiaowei qiaowei 4.0K Oct  5 22:51 CMakeFiles
drwxrwxr-x. 7 qiaowei qiaowei 4.0K Oct  5 22:45 src
-rw-rw-r--. 1 qiaowei qiaowei 1.9K Oct  5 22:45 cmake_install.cmake
-rw-rw-r--. 1 qiaowei qiaowei 9.0K Oct  5 22:45 Makefile
-rw-rw-r--. 1 qiaowei qiaowei  13K Oct  5 22:45 CMakeCache.txt
[qiaowei@clust1 build]$ cd ../..
[qiaowei@clust1 Blacklist]$ ;
-bash: syntax error near unexpected token `;'
[qiaowei@clust1 Blacklist]$ l
total 68K
drwxrwxr-x. 9 qiaowei qiaowei 4.0K Oct  5 22:51 bamtools
drwxrwxr-x. 3 qiaowei qiaowei 4.0K Oct  5 22:40 lists
drwxrwxr-x. 4 qiaowei qiaowei   68 Oct  5 22:29 demo
-rw-rw-r--. 1 qiaowei qiaowei  14K Oct  5 22:29 blacklist.cpp
-rw-rw-r--. 1 qiaowei qiaowei 4.0K Oct  5 22:29 README.md
-rw-rw-r--. 1 qiaowei qiaowei  35K Oct  5 22:29 LICENSE
-rw-rw-r--. 1 qiaowei qiaowei 1.3K Oct  5 22:29 Makefile
[qiaowei@clust1 Blacklist]$ make
g++ -std=c++14 -o Blacklist blacklist.cpp -I/mnt/disk1/qiaowei/reference/Blacklist/bamtools/install/include/bamtools -L/mnt/disk1/qiaowei/reference/Blacklist/bamtools/install/lib/bamtools -lbamtools -lz -Wl,-rpath,/mnt/disk1/qiaowei/reference/Blacklist/bamtools/install/lib/bamtools
**g++: error: unrecognized command line option ‘-std=c++14’
make: *** [all] Error 1**
` 
I know you said this installation needed Linux: Ubuntu 18.04, so that is to say I cannot use this Blacklist?or how can I fix my problem?
Thank you so much in advance.

**Comment by qiaowei-vvjoe** [comment]
sorry for that wrong format,I attach the log file.
[install.Blacklist.log](https://github.com/Boyle-Lab/Blacklist/files/3693408/install.Blacklist.log)

**Comment by aboyle** [comment]
Your C++ compiler does not support C++14 standard (-std=c++14), which is required. Please upgrade your compiler.
