### ISSUE TITLE
Minimum number of inputs

### ISSUE THREAD

**Issue by sklasfeld** [Boyle-Lab/Blacklist#5]
I used 13 bam files for the input and the program called most of the genome to be part of the blacklist. Is there a minimum number of inputs that need to be used? If so, how many? If not, what could be the issue?

**Comment by aboyle** [comment]
This shouldn't be able to happen without some strange edge cases. Are there large regions with no signal in your mappability file or in the bam files? How big is the genome you are blacklisting?

Normally we would recommend many more input files. We used 1256, 287, 443, and 490 for human, mouse, fly, and worm.

**Comment by sklasfeld** [comment]
The genome we are using is ~120 Mb. Do you have a list somewhere of where we can find the bam files that were used  to generate the human, mouse, fly, and worm blacklists?

**Comment by aboyle** [comment]
These files should contain the proper links to the ENCODE data used:
[dm6.metadata.controls.txt](https://github.com/Boyle-Lab/Blacklist/files/3713417/dm6.metadata.controls.txt)
[ce10.metadata.controls.txt](https://github.com/Boyle-Lab/Blacklist/files/3713418/ce10.metadata.controls.txt)
[mm10.metadata.controls.txt](https://github.com/Boyle-Lab/Blacklist/files/3713419/mm10.metadata.controls.txt)
[GRCh38.metadata.controls.txt](https://github.com/Boyle-Lab/Blacklist/files/3713420/GRCh38.metadata.controls.txt)

**Comment by sklasfeld** [comment]
I am wondering if my problem is my mappability files. Which kmers did you set for your mappability files? Do you have the fly umap file?

**Comment by aboyle** [comment]
These were made available through ENCODE/modENCODE. Was this problem resolved?

**Comment by sklasfeld** [comment]
yes
