### ISSUE TITLE
no model organism

### ISSUE THREAD

**Issue by wangmhan** [Boyle-Lab/Blacklist#6]
Is it possible to create such a blacklist for other organisms? In my case, chicken.
Thanks!

**Comment by aboyle** [comment]
Yes, this is possible but you would need a sufficient number of input data tracks for this to be possible. Note that the lowest number we used was 287. I can't provide an exact number but have not had much success < 50.

**Comment by wangmhan** [comment]
Thanks, will check to see if it is possible.
