### ISSUE TITLE
Unclear usage

### ISSUE THREAD

**Issue by Danvor** [Boyle-Lab/Blacklist#7]
Hello, 

I am trying to run the demo files but instead of numbers I get "High Signal Region" in the 4th field of the bed file.
Such as:
`Blacklist chrUn_GL456392`
`chrUn_GL456392  5200    23600   High Signal Region`

What does "High Signal Region" mean? 

Thank you.
Best,
Danvor

**Comment by aboyle** [comment]
This is expected behavior. I have updated the README to reflect this output. Please see our manuscript for a description of the regions: https://www.nature.com/articles/s41598-019-45839-z
