### ISSUE TITLE
k-mers of mappability

### ISSUE THREAD

**Issue by monnneee** [Boyle-Lab/Blacklist#8]
There are not mappabilty files of pig genome. We have generated uint8 Umap files based on different k-mers. However, the numbers and genome coverages of blacklist regions we identifed were much different between diffetent k-mers.  So how can we choose the most suitable k-mers  to identify blacklist ? 

Thanks!

**Comment by aboyle** [comment]
The most suitable are the closest to the read length of your sequences. At some point there are diminishing returns though so 50bp kmers for 100bp reads are probably fine.

**Comment by monnneee** [comment]
Thank you for this valuable suggestion!

**Comment by Simple53** [comment]
Hi, I am confused about how to generate the input unit8 Umap files. Is there any useful tools? Thanks.

**Comment by yueyuanxu** [comment]
> Hi, I am confused about how to generate the input unit8 Umap files. Is there any useful tools? Thanks.

I used Umap software: https://bismap.hoffmanlab.org/

**Comment by Simple53** [comment]
Thanks!

> > Hi, I am confused about how to generate the input unit8 Umap files. Is there any useful tools? Thanks.
> 
> I used Umap software: https://bismap.hoffmanlab.org/
